// utils/data.js

export const countries = [
  {
    name: 'China (CN)',
    flag: '/assets/china.png',
    discounted: '150000 PKR',
    actual: '250000 PKR',
    discount: '40% OFF',
  },
  {
    name: 'Germany (DE)',
    flag: '/assets/ger.png',
    discounted: '135000 PKR',
    actual: '150000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'Germany (DE)',
    flag: '/assets/ger.png',
    discounted: '135000 PKR',
    actual: '150000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'Germany (DE)',
    flag: '/assets/ger.png',
    discounted: '135000 PKR',
    actual: '150000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'Germany (DE)',
    flag: '/assets/ger.png',
    discounted: '135000 PKR',
    actual: '150000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'Germany (DE)',
    flag: '/assets/ger.png',
    discounted: '135000 PKR',
    actual: '150000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'Malaysia (ML)',
    flag: '/assets/mali.png',
    discounted: '45000 PKR',
    actual: '50000 PKR',
    discount: '10% OFF',
  },
  {
    name: 'United Kingdom (GB)',
    flag: '/assets/uni.png',
    discounted: '9000 PKR',
    actual: '30000 PKR',
    discount: '70% OFF',
  },
];
export const coursesData = {
  'Accounting, Finance': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Business, Management': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Computer Science & Technology': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Education, Teaching': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Engineering': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Hotel Management': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Industrial Design': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Actuarial Studies': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Agriculture': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Architecture': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Arts': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
  'Aviation': [
    'Finance (Fudan University)',
    'Master of Finance (Fudan University)',
    'Finance (Tsinghua University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
    'Finance Engineering (Wuhan University)',
    'Accounting (Wuhan University)',
  ],
};


