export const universities = [
 {
   id: 1,
   name: "Zhijiang University",
   location: "Hangzhou, China",
   logo: "/assets/s1.png",
   discountedFee: 150000,
   actualFee: 250000,
   discount: 40,
   courses: 595,
   deadline: "March, September",
   color: "bg-blue-600",
   country: "China",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: true
 },
 {
   id: 2,
   name: "York University",
   location: "Toronto, Canada",
   logo: "/assets/s1.png",
   discountedFee: 120000,
   actualFee: 200000,
   discount: 50,
   courses: 389,
   deadline: "March, September",
   color: "bg-red-600",
   country: "Canada",
   qualifications: ["Bachelor", "Masters"],
   hasScholarship: false
 },
 {
   id: 3,
   name: "COMSATS UNIVERSITY",
   location: "Islamabad, Pakistan",
   logo: "/assets/s1.png",
   discountedFee: 84000,
   actualFee: 120000,
   discount: 30,
   courses: 143,
   deadline: "September, January",
   color: "bg-green-600",
   country: "Pakistan",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: true
 },
 {
   id: 4,
   name: "Western University",
   location: "Ontario, Canada",
   logo: "/assets/s1.png",
   discountedFee: 120000,
   actualFee: 240000,
   discount: 50,
   courses: 243,
   deadline: "March, September",
   color: "bg-purple-600",
   country: "Canada",
   qualifications: ["Bachelor", "Masters"],
   hasScholarship: false
 },
 {
   id: 5,
   name: "Wuhan University",
   location: "Wuhan, China",
   logo: "/assets/s1.png",
   discountedFee: 155000,
   actualFee: 290000,
   discount: 47,
   courses: 530,
   deadline: "March, September",
   color: "bg-gray-600",
   country: "China",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: true
 },
 {
   id: 6,
   name: "University of Toronto",
   location: "Toronto, Canada",
   logo: "/assets/s1.png",
   discountedFee: 120000,
   actualFee: 240000,
   discount: 50,
   courses: 501,
   deadline: "March, September",
   color: "bg-blue-800",
   country: "Canada",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: false
 },
 {
   id: 7,
   name: "Université Laval",
   location: "Quebec, Canada",
   logo: "/assets/s1.png",
   discountedFee: 120000,
   actualFee: 240000,
   discount: 50,
   courses: 500,
   deadline: "September, January",
   color: "bg-red-700",
   country: "Canada",
   qualifications: ["Bachelor", "Masters"],
   hasScholarship: true
 },
 {
   id: 8,
   name: "University of Ottawa",
   location: "Ottawa, Canada",
   logo: "/assets/s1.png",
   discountedFee: 120000,
   actualFee: 240000,
   discount: 50,
   courses: 464,
   deadline: "March, September",
   color: "bg-red-800",
   country: "Canada",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: false
 },
 {
   id: 9,
   name: "McGill University",
   location: "Montreal, Canada",
   logo: "/images/universities/mcgill.png",
   discountedFee: 120000,
   actualFee: 240000,
   discount: 50,
   courses: 448,
   deadline: "September, January",
   color: "bg-red-600",
   country: "Canada",
   qualifications: ["Bachelor", "Masters", "Doctorate"],
   hasScholarship: true
 },
 {
   id: 10,
   name: "San José State University",
   location: "San José, USA",
   logo: "/images/universities/sanjose.png",
   discountedFee: 150000,
   actualFee: 250000,
   discount: 40,
   courses: 478,
   deadline: "March, September",
   color: "bg-teal-600",
   country: "USA",
   qualifications: ["Bachelor", "Masters"],
   hasScholarship: false
 }
];
